### ISSUE TITLE
Error while starting Apache service

### ISSUE THREAD

**Issue by mariantanase** [Bearsampp/module-apache#6]
When I try to start neard (v.1.8.2) with apache2.4.51 downloaded module, it shows this error:

![error-starting-apache2451](https://user-images.githubusercontent.com/3976174/144227095-0b661785-3985-4a26-8cd6-45a9aea0d763.png)

**Comment by N6REJ** [comment]
I dont' get that with 1.8.3-rc1.
I'm not going to try to stay compatible with "neard".  Too many changes going on to do so.
Almost every module is going thru updates.
in your case, the pathing is exactly the same as in neard ( I doubt that will change )
```
Define NEARD_LIN_PATH "~NEARD_LIN_PATH~"
Define SRVROOT "${NEARD_LIN_PATH}/bin/apache/apache2.4.51"
ServerRoot "${SRVROOT}"
```
